### ISSUE TITLE
Error with SatUplink/MoreLogisticSlots

### ISSUE THREAD

**Issue by Choumiko** [Choumiko/AutoTrash#14]
https://forums.factorio.com/viewtopic.php?f=97&t=16016&view=unread#p241380

**Comment by doppynl** [comment]
Looking at the code it determines the logistic slot count based on the research done.
This will fail when other mods add slots (or some other method of adding slots is added in the future).

The code should not calculate this amount itself, but simply read the correct property on the player.
See: http://lua-api.factorio.com/0.16.36/LuaForce.html#LuaForce.character_logistic_slot_count
