### ISSUE TITLE
LuaGuiElement doesn't contain key can_scroll_horizontally

### ISSUE THREAD

**Issue by decitrig** [Choumiko/AutoTrash#15]
When I try and open the autotrash GUI, I get the error message in the title. It seems to be complaining about this line: https://github.com/Choumiko/AutoTrash/blob/ca3a686bd371afb661a40718eea8a52da80a070e/gui.lua#L263

Here's a save game where this can be reproduced:
[ryan016.zip](https://github.com/Choumiko/AutoTrash/files/1598358/ryan016.zip)

**Comment by Choumiko** [comment]
fixed in the latest update
fixed in 3f5c075ed9e0e2201fdb5dc31adb499c183c0058
