### ISSUE TITLE
Crash in on_robot_pre_mined.

### ISSUE THREAD

**Issue by CyaNox** [Choumiko/AutoTrash#16]
```
233952.863 Error MainLoop.cpp:1029: Exception at tick 44867695: Error while running event AutoTrash::on_robot_pre_mined (ID 15)
__AutoTrash__/control.lua:335: attempt to index field 'logistic_network' (a nil value)
```

I changed: https://github.com/Choumiko/AutoTrash/blob/master/control.lua#L332 to: `if entity == event.entity and entity.logistic_network then` and this fixes it.

**Comment by Choumiko** [comment]
Couldn't reproduce it, but should be fixes anyways in the latest update. Thanks for the report.
