### ISSUE TITLE
[4.0.5] Auto Trash stopped working

### ISSUE THREAD

**Issue by Yousei9** [Choumiko/AutoTrash#18]
AutoTrash seems unable to set trash requests.

![2019-05-23-10-02-02-0127026](https://user-images.githubusercontent.com/8436934/58236022-4e828180-7d42-11e9-9ebe-160461c6e6e3.png)

Perhaps some instances of player where not properly migrated to character.

**Comment by Choumiko** [comment]
What the..
https://github.com/Choumiko/AutoTrash/commit/3d9ace84c731fb4e397e7f94173e7ce258a386f4#diff-2f29ee9c98c28d035046fb40285456daR32
I'm surprised it didn't error, seems like an alive player still has a character corpse inventory :D

**Comment by Choumiko** [comment]
fixed in the latest update

**Comment by Yousei9** [comment]
Living characters with corpse inventories really sound weird.
Maybe mods can abuse that to have characters carry things around players are not supposed to see.
